### ISSUE TITLE
3.2.2 版本 esbuild 构建结果运行报错

### ISSUE THREAD

**Issue by eternalsky** [yusangeng/mix-with#4]
3.2.2 版本指定了 type:module ，但是没有follow node 的 conditional exports，导致如果 mix-with 是被 require 的话，esbuild 会去读 main 而不是 module，但是因为 type 指定为了 module，esbuild 又会把他当做 esm 去处理，导致构建结果在浏览器运行出错，表现为 exports is not defined。

建议：
1. 去掉 type: module ，仍然提供 main 和 module 给 bundler 使用。或者
2. 加上 conditional exports 

参考：
https://nodejs.org/api/packages.html#type
https://esbuild.github.io/api/#conditions
https://esbuild.github.io/api/#platform

**Comment by yusangeng** [comment]
3.2.4版本的package.json添加了exports字段：

```
  "exports": {
    ".": "./esm/index.js"
  },
```

保证使用require的时候esbuild仍然会加载到esm module文件。

使用esbuild bundle的demo：https://github.com/yusangeng/esbuild-bundle-mix-with-demo
